//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faden_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int IdAcceso { get; set; }
        public int IdRol { get; set; }
        public bool Seleccionar { get; set; }
        public bool EsMenu { get; set; }
        public string Modulo { get; set; }
        public string ModuloNombre { get; set; }
        public string Id { get; set; }
        public string Link { get; set; }
        public string MenuPadre { get; set; }
        public string Clase { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
