//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faden_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acompanante
    {
        public int IdAcpte { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public bool EsAcpte { get; set; }
        public bool EsCuidador { get; set; }
        public bool EsPrimario { get; set; }
        public bool EsSecundario { get; set; }
        public int IdPaciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
