//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faden_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstiloVida
    {
        public int IdEstiloVida { get; set; }
        public string Senderismo { get; set; }
        public string Alcoholismo { get; set; }
        public string Tabaquismo { get; set; }
        public string Cafe { get; set; }
        public string Ruido { get; set; }
        public string Horas { get; set; }
        public string Despertar { get; set; }
        public int IdPaciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
