//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faden_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public int IdPerfil { get; set; }
        public int IdUsuario { get; set; }
        public string Acceso { get; set; }
        public bool Activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
